export const GET_ERROR = 'GET_ERROR';
export const CLEAR_ERROR = 'CLEAR_ERROR';

export const USER_LOADING = 'USER_LOADING';
export const PROFILE_LOADING = 'USER_LOADING';
export const POLL_LOADING = 'POLL_LOADING';

export const USER_SIGN_IN = 'USER_SIGN_IN';
export const USER_SIGN_IN_FAILURE = 'USER_SIGN_IN_FAILURE';

export const USER_SIGN_UP = 'USER_SIGN_UP';
export const CHECK_USERNAME_AVAIL = 'CHECK_USERNAME_AVAIL';
export const CHECK_EMAIL_AVAIL = 'CHECK_EMAIL_AVAIL';
export const CLEAR_USERNAME_VALIDATION = 'CLEAR_USERNAME_VALIDATION';
export const CLEAR_EMAIL_VALIDATION = 'CLEAR_EMAIL_VALIDATION';
export const USER_SIGN_UP_FAILURE = 'USER_SIGN_UP_FAILURE';
export const USER_SIGN_UP_SUCCESS = 'USER_SIGN_UP_SUCCESS';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const GET_CURRENT_USER = 'GET_CURRENT_USER';
export const CLEAR_CURRENT_USER = 'CLEAR_CURRENT_USER';
export const CLEAR_CURRENT_PROFILE = 'CLEAR_CURRENT_PROFILE';

export const GET_PROFILE = 'GET_PROFILE';
export const SET_PROFILE = 'SET_PROFILE';

export const GET_USER_CREATED_POLLS = 'GET_USER_CREATED_POLLS';
export const GET_USER_VOTED_POLLS = 'GET_USER_VOTED_POLLS';
export const GET_ALL_POLLS = 'GET_ALL_POLLS';

export const POLL_RESET = 'POLL_RESET';

export const CREATE_POLL = 'CREATE_POLL';
export const CLEAR_POLL_RES = 'CLEAR_POLL_RES';
export const CAST_VOTE = 'CAST_VOTE';
export const CLEAR_VOTE_RES = 'CLEAR_POLL_RES';
